### ISSUE TITLE
APM won't work in Fedora 24

### ISSUE THREAD

**Issue by alex94cp** [FZUG/repo#105]
It fails with the following output:

```
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by 1dot75cm** [comment]
Thanks report. Please update to [nodejs-atom-package-manager-1.10.0-2.git87b4bcb.fc24.x86_64.rpm](https://copr-be.cloud.fedoraproject.org/results/mosquito/atom/fedora-24-x86_64/00280608-nodejs-atom-package-manager/nodejs-atom-package-manager-1.10.0-2.git87b4bcb.fc24.x86_64.rpm). @alex94puchades

**Comment by alex94cp** [comment]
Thanks @1dot75cm, that worked! Should I close the issue or wait until the rpm is pushed to the copr repo?

**Comment by 1dot75cm** [comment]
The rpm is pushed to the [Copr repo](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/280608/).
