### ISSUE TITLE
Atom package management broken?

### ISSUE THREAD

**Issue by lucascosti** [FZUG/repo#114]
Hi,

Since the latest Atom and electron update, the package management inside atom seems to be broken.

I get similar `Error: Cannot find module 'app'` errors whenver trying to update/view/install atom packages. This doesn't happen if I install the atom RPM from https://atom.io/.

Installed Atom versions from the mosquito-atom repo:

atom   x86_64        1.7.4-1.git6bed3e5.fc23          mosquito-atom
 electron    x86_64        1.2.0-1.prebuilt.fc23            mosquito-atom
 nodejs-atom-package-manager    x86_64        1.10.0-5.git87b4bcb.fc23         mosquito-atom

**Atom Version**: 1.7.4
**System**: "Fedora release
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package, v0.235.1
### Stack Trace

Uncaught Error: Cannot find module 'app'
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/usr/lib64/electron/resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/rpc-server.js:226:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)

```
At /usr/lib64/electron/resources/electron.asar/renderer/api/remote.js:178

Error: Cannot find module 'app'
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/usr/lib64/electron/resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/rpc-server.js:226:70)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/api/web-contents.js:139:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at metaToValue (/usr/lib64/electron/resources/electron.asar/renderer/api/remote.js:178:13)
    at AtomIoClient.module.exports.AtomIoClient.getCachePath (/usr/lib64/atom/node_modules/settings-view/lib/atom-io-client.js:271:90)
    at AtomIoClient.module.exports.AtomIoClient.createAvatarCache (/usr/lib64/atom/node_modules/settings-view/lib/atom-io-client.js:162:31)
    at new AtomIoClient (/usr/lib64/atom/node_modules/settings-view/lib/atom-io-client.js:24:12)
    at PackageManager.module.exports.PackageManager.getClient (/usr/lib64/atom/node_modules/settings-view/lib/package-manager.js:28:64)
    at InstallPanel.module.exports.InstallPanel.initialize (/usr/lib64/atom/node_modules/settings-view/lib/install-panel.js:135:41)
    at InstallPanel.View [as constructor] (/usr/lib64/atom/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at InstallPanel.ScrollView [as constructor] (/usr/lib64/atom/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new InstallPanel (/usr/lib64/atom/node_modules/settings-view/lib/install-panel.js:32:49)
    at /usr/lib64/atom/node_modules/settings-view/lib/settings-view.js:159:18
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (/usr/lib64/atom/node_modules/settings-view/lib/settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (/usr/lib64/atom/node_modules/settings-view/lib/settings-view.js:320:24)
    at HTMLAnchorElement.<anonymous> (/usr/lib64/atom/node_modules/settings-view/lib/settings-view.js:123:24)
    at space-pen-div.dispatch (/usr/lib64/atom/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/usr/lib64/atom/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -8:00.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "whitespace"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "open-plus"
    ],
    "projectHome": "/home/lcosti/repos/eap-documentation"
  }
}
```
### Installed Packages

``` coffee
# User
asciidoc-preview, v1.0.4
color-picker, v2.1.1
file-icons, v1.7.12
language-asciidoc, v1.4.5
linter, v1.11.4
linter-xmllint, v1.3.4
merge-conflicts, v1.4.3
minimap, v4.24.2
minimap-bookmarks, v0.3.1
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.1
minimap-git-diff, v4.3.1
minimap-selection, v4.4.0
open-plus, v0.10.1
open-recent, v5.0.0
pigments, v0.27.1
rename-tabs, v0.1.1

# Dev
No dev packages
```

**Comment by 1dot75cm** [comment]
Thanks test. @lucascosti
I try to update `settings-view` package to v0.237.0. It works correctly.

```
$ apm install settings-view@0.237.0 --verbose
```

**Comment by 1dot75cm** [comment]
Please test [atom-1.7.4-2.git6bed3e5.fc23](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/317970/) rpm package. @lucascosti

**Comment by lucascosti** [comment]
@1dot75cm looks to be working now, thanks!
