### ISSUE TITLE
Atom loops on missing module shortest_path_tree on F24

### ISSUE THREAD

**Issue by xenithorb** [FZUG/repo#185]
Noticed recently heavy CPU usage from atom, it seems to be looping on the following error: 

```
[31751:1017/165121:INFO:CONSOLE(52)] "Cannot find module './util/shortest_path_tree'", source: /builddir/build/BUILD/atom-099ffefca36057084aac3d55748f35cf6c3bcae6/out/app/src/task.coffee (52)
```

I uninstalled from the COPR repository, installed the official RPM and the problem doesn't occur. I also removed that and installed from COPR again and the problem re-appeared. It also happens with `atom -f --safe` and doesn't appear to be related to anything in my `~/.atom`

**Comment by xenithorb** [comment]
It seems to be triggered _only_ after having a window layout with a file that would normally be spell-checked. i.e. You can't cause the bug by opening atom in a new folder and then opening files. It's triggered only after a layout is already present with one of these files. 

```
/builddir/build/BUILD/atom-099ffefca36057084aac3d55748f35cf6c3bcae6/out/app/src/task.coffee:52 Cannot find module './util/shortest_path_tree' Error: Cannot find module './util/shortest_path_tree'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/usr/lib64/atom/node_modules/spell-check/node_modules/spelling-manager/node_modules/natural/lib/natural/index.js:64:28)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/usr/lib64/atom/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/lib64/atom/node_modules/spell-check/node_modules/spelling-manager/lib/init.js:15:19
    at /usr/lib64/atom/node_modules/spell-check/node_modules/spelling-manager/lib/init.js:8:17
    at Object.<anonymous> (/usr/lib64/atom/node_modules/spell-check/node_modules/spelling-manager/lib/init.js:13:3)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/usr/lib64/atom/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at new KnownWordsChecker (/usr/lib64/atom/node_modules/spell-check/lib/known-words-checker.js:13:25)
    at SpellCheckerManager.init (/usr/lib64/atom/node_modules/spell-check/lib/spell-check-manager.js:327:34)
    at SpellCheckerManager.check (/usr/lib64/atom/node_modules/spell-check/lib/spell-check-manager.js:104:12)
    at Object.backgroundCheck (/usr/lib64/atom/node_modules/spell-check/lib/spell-check-handler.js:25:29)
    at process.<anonymous> (/usr/lib64/atom/src/task-bootstrap.js:84:10)
    at emitTwo (events.js:105:20)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```
