### ISSUE TITLE
仓库中的atom的apm包管理器无法使用

### ISSUE THREAD

**Issue by ljhui** [FZUG/repo#242]
系统是4.10.17-100.fc24.x86_64
每次update,就会show output:
```
/usr/lib/node_modules/atom-package-manager/lib/fs.js:42
  module.exports = new Proxy({}, {
                       ^

ReferenceError: Proxy is not defined
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/lib/fs.js:42:24)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/lib/fs.js:51:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/lib/apm.js:6:8)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/lib/apm.js:164:4)
```
也无法查看已经安装的包，应该是nodejs-atom-package-manager有bug,能否更新一下？

**Comment by sztsian** [comment]
Hi, 
由于中文用户组repo维护者有限，我们无法及时回复，请谅解。
请问能否提供一下触发这个bug的具体命令？

**Comment by ljhui** [comment]
只要是跟apm相关的命令都会出现这个，比如apm install <package>安装某个包都会出现这个，甚至查看apm版本和帮助apm --v ,apm --help 都无法使用，我试着降级atom回以前的版本没问题，不过最后还是从官网下载最新的atom1.18安装解决了
