### ISSUE TITLE
mosquito/atom needs to add F27 build target for beta users.

### ISSUE THREAD

**Issue by xenithorb** [FZUG/repo#276]
Unfortunately when one would normally just upgrade and wait for the COPR repo to catch up, this time `apm` breaks with: 

```
module.js:653
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:371:4)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

And thus all package operations in `atom` itself are broken, too...

I tried rebuilding the module with `npm rebuild` as a temporary workaround, but that didn't work either so it would be awesome if you could provide an updated branch so that `atom-package-manager` gets rebuilt against F27. Thanks

Note: There's also a "Follow fedora branching" setting in COPR now

**Comment by alick** [comment]
Sorry that I'll close the issue. Please contact @1dot75cm aka mosquito directly to report issues of his Copr projects. Here is for software in the FZUG repo.
