### ISSUE TITLE
[bcloud]No module named 'pyinotify'

### ISSUE THREAD

**Issue by sztsian** [FZUG/repo#36]
$ bcloud-gui 
Traceback (most recent call last):
  File "/usr/bin/bcloud-gui", line 11, in <module>
    from bcloud.App import App
  File "/usr/lib/python3.4/site-packages/bcloud/App.py", line 37, in <module>
    from bcloud.FileWatcher import WatchFileChange
  File "/usr/lib/python3.4/site-packages/bcloud/FileWatcher.py", line 8, in <module>
    import pyinotify
ImportError: No module named 'pyinotify'

**Comment by sztsian** [comment]
After I manually installed python3-inotify it works well.So fixed in pr#37. Please review. SPEC not tested

**Comment by 1dot75cm** [comment]
已确认，待测试。bcloud 在 23 有更严重的错误。

**Comment by 1dot75cm** [comment]
The bcloud is being refactoring. Currently, it does not work on the fc23. In fc22, work fine.

**Comment by 0xbitx** [comment]
pip install pyinotify
