### ISSUE TITLE
QT的那个网易云音乐客户端事实上不能使用...

### ISSUE THREAD

**Issue by evolighting** [FZUG/repo#72]
所以我是不是需要在KDE下才能使用这个玩意......

有个啥qt的库找不到....

然而我已经转下载党了.....

**Comment by 1dot75cm** [comment]
feeluown 这货吗？ 请终端运行 feeluown 贴出错误日志。

**Comment by Endle** [comment]
$ feeluown
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/feeluown/main.py", line 11, in <module>
    from quamash import QEventLoop
ImportError: No module named 'quamash'

运行一下 quamash 就好了
（所以是python依赖的问题）

**Comment by 1dot75cm** [comment]
我在安装脚本里写的是 `/usr/bin/pip3 install -U -q 'quamash==0.5.3'`。 不知道为什么，没有运行成功。

**Comment by Endle** [comment]
我们打一个 python3-quamash 的包会不会很麻烦？或者是向 fedora repo 上提交这个？

**Comment by evolighting** [comment]
@Endle @1dot75cm 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/feeluown/main.py", line 34, in <module>
    from feeluown.glue import Glue
  File "/usr/lib/python3.4/site-packages/feeluown/glue.py", line 27, in <module>
    from feeluown.ui import UiMainWidget
  File "/usr/lib/python3.4/site-packages/feeluown/ui.py", line 14, in <module>
    from feeluown.right_widget import RightWidget
  File "/usr/lib/python3.4/site-packages/feeluown/right_widget.py", line 15, in <module>
    from feeluown.widgets.webview import WebView
  File "/usr/lib/python3.4/site-packages/feeluown/widgets/webview.py", line 5, in <module>
    from PyQt5.QtWebKitWidgets import QWebView
ImportError: libQt5WebKitWidgets.so.5: cannot open shared object file: No such file or directory

然后我发现，我并没有QT5.....
所以问题变成了fedora23如何安装pyqt5？

Last metadata expiration check performed 2:15:27 ago on Wed Mar  9 16:28:50 2016.
Package python3-qt5-5.5.1-2.fc23.x86_64 is already installed, skipping.

另外这个包装了还是要另一个么？

# 

更新，我算是一个个吧依赖安装了，然后就好了；

所以问题是有办法吧这些QT的依赖一口气都装了么？

**Comment by 1dot75cm** [comment]
python3-qt5 是依赖 qt5 的，使用 dnf 安装会解决 QT 的依赖。@evolighting

打包 python3-quamash 应该没问题，主要是我犯懒了。 @Endle

**Comment by sztsian** [comment]
问题算是解决了嘛？如果是，请关闭issue @evolighting
