### ISSUE TITLE
The latest build of Atom can't work with packages

### ISSUE THREAD

**Issue by paulcarroty** [FZUG/repo#88]
Tested on Fedora 25: 

https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/174997/
https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/175165/

```
$ apm -vvv
apm  1.9.2
npm  3.8.3
node 5.10.1
python 2.7.11
git 2.8.1
```

`apm` work in console with no issues.

**Comment by 1dot75cm** [comment]
I just tested on Fedora 25. It's no issues.
Please provide error logs. @paulcarroty 

![](http://imgsrc.baidu.com/forum/pic/item/329c93cad1c8a786925743a06009c93d71cf50a5.jpg)

**Comment by paulcarroty** [comment]
``` JavaScript
/usr/lib64/atom/node_modules/settings-view/lib/installed-packages-panel.js:330 Fetching local packages failed. Error: Fetching local packages failed.
    at createJsonParseError (/usr/lib64/atom/node_modules/settings-view/lib/package-manager.js:695:13)
    at /usr/lib64/atom/node_modules/settings-view/lib/package-manager.js:97:23
    at exit (/usr/lib64/atom/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/lib64/atom/src/buffered-process.js:215:47)
    at /usr/lib64/atom/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/lib64/atom/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)(anonymous function) @ /usr/lib64/atom/node_modules/settings-view/lib/installed-packages-panel.js:330
/usr/lib64/atom/node_modules/settings-view/lib/installed-packages-panel.js:331 Uncaught (in promise) TypeError: Cannot read property 'hide' of undefined
    at /usr/lib64/atom/node_modules/settings-view/lib/installed-packages-panel.js:331:31
```

**Comment by 1dot75cm** [comment]
Hi, @paulcarroty . I do not see any similar errors. How to reproduce the error?

```
[localhost ~]$ rpm -qa atom
atom-1.7.0-1.git1e7dc02.fc25.x86_64
[localhost ~]$ rpm -qa nodejs-atom-package-manager
nodejs-atom-package-manager-1.9.2-5.gitdef66c9.fc25.x86_64
[localhost ~]$ atom -v
Atom    : 1.7.0
Electron: 0.37.5
Chrome  : 49.0.2623.75
Node    : 5.10.0
[localhost ~]$ apm -v
apm  1.9.2
npm  3.8.3
node 5.10.1
python 2.7.11
git 2.8.1
[localhost ~]$ electron -v
v0.37.5
```

**Comment by paulcarroty** [comment]
@1dot75cm, open "Settings -> Packages" and see the infinite "Loading packages...". Logs from Developer Tools Console. I will try also the clean installation.

**Comment by paulcarroty** [comment]
`<blockquote class="imgur-embed-pub" lang="en" data-id="lCeYIlr"><a href="//imgur.com/lCeYIlr">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

**Comment by paulcarroty** [comment]
![](http://i.imgur.com/lCeYIlr.png)

**Comment by paulcarroty** [comment]
``` JavaScript
$ apm update 
Package Updates Available (3)
├── atom-runner 2.5.3 -> 2.6.0
├── file-icons 1.7.1 -> 1.7.2
└── markdown-writer 2.3.2 -> 2.3.3

Would you like to install these updates? (yes) y

Installing atom-runner@2.6.0 to /home/paul/.atom/packages 
assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: Expected there to only be one child in node_modules
    at /usr/lib/node_modules/atom-package-manager/lib/install.js:167:22
    at ChildProcess.onChildExit (/usr/lib/node_modules/atom-package-manager/lib/command.js:53:49)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

**Comment by 1dot75cm** [comment]
Fix this error. Please test it. [175420](https://copr.fedorainfracloud.org/coprs/mosquito/atom/build/175420/) @paulcarroty

**Comment by 1dot75cm** [comment]
Fixes `apm install` command for fc25. But see the infinite "Loading packages...".

```
Fetching local packages failed. Error: Fetching local packages failed.
    at createJsonParseError (/usr/lib64/atom/node_modules/settings-view/lib/package-manager.js:695:13)
    at /usr/lib64/atom/node_modules/settings-view/lib/package-manager.js:97:23
    at module.exports.PackageManager.runCommand.exit (/usr/lib64/atom/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/usr/lib64/atom/src/buffered-process.js:215:47)
    at /usr/lib64/atom/src/buffered-process.js:229:18
    at Socket.<anonymous> (/usr/lib64/atom/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

**Comment by paulcarroty** [comment]
The same. No idea to fix it (:   Maybe troubles with `electron`? The official build still use `Electron 0.36.8`. and `npm  2.13.3`.

**Comment by 1dot75cm** [comment]
Hi @paulcarroty . There is a strange question. The output of `apm ls --json` incomplete on Fedora 25.  (The official build `apm` is work fine.)

```
$ apm -v   (fc25)
apm  1.9.2
npm  3.8.3
node 5.10.1
python 2.7.11
git 2.8.1
$ apm list --json | wc -c  <---- fc25, incomplete
65536   (Byte)

$ apm -v   (fc23)
apm  1.9.2
npm  1.3.6
node 0.10.42
python 2.7.11
git 2.5.5
$ apm list --json | wc -c  <---- fc23, complete
4016429  (Byte)
```

I try to add `length` to view JSON length. no problem.

```
$ vim /usr/lib/node_modules/atom-package-manager/lib/list.js
.....
    List.prototype.listPackagesAsJson = function(options, callback) {
......
      console.log(JSON.stringify(output).length);
$ apm list --json
147591
```

Maybe troubles with latest `node` or `npm`. Mayby the system also be limited.
